# Generated by Django 4.0.1 on 2022-01-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_id', models.IntegerField()),
                ('clinic_name', models.CharField(max_length=60)),
                ('physician_id', models.IntegerField()),
                ('physician_name', models.CharField(max_length=100)),
                ('physician_crm', models.CharField(max_length=15)),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=60)),
                ('patient_email', models.CharField(max_length=40)),
                ('patient_phone', models.CharField(max_length=40)),
                ('prescription_id', models.IntegerField()),
            ],
        ),
    ]
