# Generated by Django 4.0.1 on 2022-01-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_id', models.IntegerField()),
                ('physician_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('prescription_name', models.CharField(max_length=100)),
            ],
        ),
    ]
